[project]
name = "simple-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.21.2",
]
[project.scripts]
simple-mcp-server = "server:main"
